events {}

http {
    log_format main '$remote_addr -> $upstream_addr  XFF=[$http_x_forwarded_for]';
    access_log /var/log/nginx/access.log main;

    upstream app_direct {
        server app:8000;
    }

    upstream via_nginx3 {
        server nginx3:80;
    }

    server {
        listen 80;

        location /direct/ {
            # Любой XFF, пришедший от клиента, отбрасывается.
            proxy_set_header X-Forwarded-For $remote_addr;

            # Передаём имя текущего nginx в цепочку (удобно для дебага)
            proxy_set_header X-Proxy-Path "nginx1";

            proxy_pass http://app_direct/;
        }
        
        location /chain/ {
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Proxy-Path "nginx1";

            proxy_pass http://via_nginx3/;
        }
    }
}
