events {}

http {
    log_format main '$remote_addr -> $upstream_addr  XFF=[$http_x_forwarded_for]';
    access_log /var/log/nginx/access.log main;

    upstream app_direct {
        server app:8000;
    }

    server {
        listen 80;

        location / {
            # добавляем IP предыдущего прокси в цепочку
            proxy_set_header X-Forwarded-For "$http_x_forwarded_for, $remote_addr";
            # дополняем путь для наглядности
            proxy_set_header X-Proxy-Path "$http_x_proxy_path, nginx3";

            proxy_pass http://app_direct/;
        }
    }
}
