events {}

http {
    log_format main '$remote_addr -> $upstream_addr  XFF=[$http_x_forwarded_for]';
    access_log /var/log/nginx/access.log main;

    upstream app_direct {
        server app:8000;
    }

    server {
        listen 80;

        location / {
            # Перезаписываем XFF: реальный IP клиента
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Proxy-Path "nginx2";

            proxy_pass http://app_direct/;
        }
    }
}
